# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "kimmy-app"
compatibility_date = "2025-04-01"
main = "./workers/app.ts"
upload_source_maps = true

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
ADMIN_EMAIL = "admin@kimmy-app.com"
VITE_R2_PUBLIC_URL = "https://kimmy-app-assets.r2.dev/"
BASE_URL = "https://kimmy-app.workers.dev/"

[observability]
enabled = true

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "kimmy_app_analytics"

[[d1_databases]]
binding = "DB"
database_name = "kimmy-app-db"
database_id = "6d9a4a6c-81c4-4338-9c5d-4c688f57091a"
migrations_dir = "./migrations"

[[r2_buckets]]
bucket_name = "kimmy-app-assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "1a2e4983299549b8958ec177909526af"
preview_id = "2a3f0f6f8e1a49d59484e79bbd046965"

[[send_email]]
# Email Routing binding for sending password reset emails
name = "KIMMY_EMAIL"

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# placement = { mode = "smart" }

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform,
# including databases, object storage, AI inference, real-time communication, and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# vars = { MY_VARIABLE = "production_value" }

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# assets = { directory = "./public/", binding = "ASSETS" }

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
